{
    'name': 'Hospital Managment System',
    'version': '1.0.0',
    'category': 'Managment',
    'author': 'Ashish Radadiya & Ajay Vadadoriya',
    'sequence': -200,
    'summary': 'Hospital Managment System',
    'description': """Handle Hospital Records With Minimum Effort""",
    'license': 'LGPL-3',
    'depends': [
        'mail','product'
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security_access.xml',
        'data/sequence_number_data.xml',
        'data/patient_reg_mail_template_data.xml',
        'wizard/bed_transfer.xml',
        'wizard/imaging_request.xml',
        'wizard/blood_transfer_wizard.xml',
        'wizard/blood_take_wizard.xml',
        'report/report.xml',
        'report/patient_data_report.xml',
        'report/patient_deceased_report.xml',
        'report/diseases_report.xml',
        'report/medication_report.xml',
        'report/vaccination_report.xml',
        'report/labtest_report.xml',
        'report/prescription_report.xml',
        'report/appointment_report.xml',
        'report/visiting_card_repot.xml',
        'report/new_born_report.xml',
        'views/icu.xml',
        'views/blood_transaction.xml',
        'views/buy_blood.xml',
        'views/ventilation.xml',
        'views/apache_II_score.xml',
        'views/surgery.xml',
        'views/medical_service.xml',
        'views/ecg.xml',
        'views/lab_test_result.xml',
        'views/draft_leb_test.xml',
        'views/gcs.xml',
        'views/patient_view.xml',
        'views/vaccinations.xml',
        'views/pediatric.xml',
        'views/new_born.xml',
        'views/blood_donors.xml',
        'views/family.xml',
        'views/patient_hospitalization.xml',
        'views/member.xml',
        'views/imaging.xml',
        'views/image.xml',
        'views/deceased.xml',
        'views/doctor_view.xml',
        'views/prescription.xml',
        'views/presline.xml',
        'views/appointment_view.xml',
        'views/employee_view.xml',
        'views/pharmacy_view.xml',
        'views/configuration_view.xml',
        'views/lab_testing_units.xml',
        'views/lab_test_type.xml',
        'views/pathology_groups.xml',
        'views/diseases.xml',
        'views/disease_categories_structure.xml',
        'views/disease_categories.xml',
        'views/imaging_test_type.xml',
        'views/imaging_test.xml',
        'views/health_center_buildings.xml',
        'views/health_center.xml',
        'views/health_center_units.xml',
        'views/health_center_wards.xml',
        'views/health_center_beds.xml',
        'views/hospital_operating_rooms.xml',
        'views/operational_areas.xml',
        'views/operational_sectors.xml',
        'views/physicians.xml',
        'views/medicament_administration_routes.xml',
        'views/medicament_form.xml',
        'views/medicament_categories_structure.xml',
        'views/medicament_categories.xml',
        'views/insurances_company.xml',
        'views/insurances.xml',
        'views/genetics_risks.xml',
        'views/medicaments.xml',
        'views/medical_specialties.xml',
        'views/medicament_units.xml',
        'views/occupations.xml',
        'views/recreational_drugs.xml',
        'views/menu.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'Ramsam_Multispeciality_Hospital/static/src/legacy/css/style.css',
        ],
    },
    'demo': [],
    'application': True,
    'auto_install': False,
}
